project_id = "rhfvvuzffcyvkqxcfjcg"

[functions.analyze-response]
verify_jwt = true

[functions.transcribe-audio]
verify_jwt = true

[functions.revenuecat-webhook]
verify_jwt = false

[functions.add-friend]
verify_jwt = false
