import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Badge } from '@/components/ui/badge';
import { ScrollArea } from '@/components/ui/scroll-area';

interface AIAnalysisDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  analysis: string;
  sentiment?: string;
  keyThemes?: string[];
}

const AIAnalysisDialog = ({
  open,
  onOpenChange,
  analysis,
  sentiment,
  keyThemes,
}: AIAnalysisDialogProps) => {
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-3xl max-h-[80vh]">
        <DialogHeader>
          <DialogTitle className="font-card text-2xl">AI Psychological Analysis</DialogTitle>
        </DialogHeader>

        <ScrollArea className="max-h-[60vh] pr-4">
          <div className="space-y-6">
            {sentiment && (
              <div>
                <h3 className="font-ui font-semibold text-sm mb-2">Emotional Tone</h3>
                <Badge variant="secondary" className="capitalize">
                  {sentiment}
                </Badge>
              </div>
            )}

            {keyThemes && keyThemes.length > 0 && (
              <div>
                <h3 className="font-ui font-semibold text-sm mb-2">Key Themes</h3>
                <div className="flex flex-wrap gap-2">
                  {keyThemes.map((theme, index) => (
                    <Badge key={index} variant="outline">
                      {theme}
                    </Badge>
                  ))}
                </div>
              </div>
            )}

            <div>
              <h3 className="font-ui font-semibold text-sm mb-3">Insights</h3>
              <div className="prose prose-sm max-w-none">
                <p className="font-ui text-foreground whitespace-pre-wrap leading-relaxed">
                  {analysis}
                </p>
              </div>
            </div>

            <div className="p-4 bg-muted/30 rounded-lg">
              <p className="text-xs text-muted-foreground font-ui">
                💡 This analysis is generated by AI and should be taken as thoughtful reflection rather than 
                professional psychological advice. Use these insights as conversation starters with your partner.
              </p>
            </div>
          </div>
        </ScrollArea>
      </DialogContent>
    </Dialog>
  );
};

export default AIAnalysisDialog;