import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Badge } from '@/components/ui/badge';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Button } from '@/components/ui/button';
import { Share2, Copy, Check } from 'lucide-react';
import { useState } from 'react';
import { toast } from 'sonner';

interface AIAnalysisDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  analysis: string;
  question?: string;
  sentiment?: string;
  keyThemes?: string[];
}

const AIAnalysisDialog = ({
  open,
  onOpenChange,
  analysis,
  question,
  sentiment,
  keyThemes,
}: AIAnalysisDialogProps) => {
  const [copied, setCopied] = useState(false);

  const buildShareText = () => {
    let text = "💕 Lovers Quarrel - AI Insights\n\n";
    
    if (question) {
      text += `Question: "${question}"\n\n`;
    }
    
    if (sentiment) {
      text += `Emotional Tone: ${sentiment}\n\n`;
    }
    
    if (keyThemes && keyThemes.length > 0) {
      text += `Key Themes: ${keyThemes.join(', ')}\n\n`;
    }
    
    text += `Insights:\n${analysis}`;
    
    return text;
  };

  const handleShare = async () => {
    const shareText = buildShareText();
    
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'Lovers Quarrel - AI Insights',
          text: shareText,
        });
        toast.success('Shared successfully!');
      } catch (error) {
        if ((error as Error).name !== 'AbortError') {
          handleCopy();
        }
      }
    } else {
      handleCopy();
    }
  };

  const handleCopy = async () => {
    const shareText = buildShareText();
    
    try {
      await navigator.clipboard.writeText(shareText);
      setCopied(true);
      toast.success('Copied to clipboard!');
      setTimeout(() => setCopied(false), 2000);
    } catch (error) {
      toast.error('Failed to copy');
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-3xl max-h-[80vh]">
        <DialogHeader className="flex flex-row items-center justify-between pr-8">
          <DialogTitle className="font-card text-2xl">AI Psychological Analysis</DialogTitle>
          <Button
            variant="outline"
            size="sm"
            onClick={handleShare}
            className="flex items-center gap-2"
          >
            {copied ? (
              <Check className="w-4 h-4" />
            ) : navigator.share ? (
              <Share2 className="w-4 h-4" />
            ) : (
              <Copy className="w-4 h-4" />
            )}
            {copied ? 'Copied!' : 'Share'}
          </Button>
        </DialogHeader>

        <ScrollArea className="max-h-[60vh] pr-4">
          <div className="space-y-6">
            {sentiment && (
              <div>
                <h3 className="font-ui font-semibold text-sm mb-2">Emotional Tone</h3>
                <Badge variant="secondary" className="capitalize">
                  {sentiment}
                </Badge>
              </div>
            )}

            {keyThemes && keyThemes.length > 0 && (
              <div>
                <h3 className="font-ui font-semibold text-sm mb-2">Key Themes</h3>
                <div className="flex flex-wrap gap-2">
                  {keyThemes.map((theme, index) => (
                    <Badge key={index} variant="outline">
                      {theme}
                    </Badge>
                  ))}
                </div>
              </div>
            )}

            <div>
              <h3 className="font-ui font-semibold text-sm mb-3">Insights</h3>
              <div className="prose prose-sm max-w-none">
                <p className="font-ui text-foreground whitespace-pre-wrap leading-relaxed">
                  {analysis}
                </p>
              </div>
            </div>

            <div className="p-4 bg-muted/30 rounded-lg">
              <p className="text-xs text-muted-foreground font-ui">
                💡 This analysis is generated by AI and should be taken as thoughtful reflection rather than 
                professional psychological advice. Use these insights as conversation starters with your partner.
              </p>
            </div>
          </div>
        </ScrollArea>
      </DialogContent>
    </Dialog>
  );
};

export default AIAnalysisDialog;