-- Create cards table
CREATE TABLE IF NOT EXISTS public.cards (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  deck_id TEXT NOT NULL,
  subtype TEXT NOT NULL,
  text TEXT NOT NULL,
  choice_a TEXT,
  choice_b TEXT,
  spice TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.cards ENABLE ROW LEVEL SECURITY;

-- Create policy for public read access (cards aren't user-specific)
CREATE POLICY "Anyone can view active cards"
ON public.cards
FOR SELECT
USING (is_active = true);

-- Insert Freaky Deck - This or That (75 cards)
INSERT INTO public.cards (deck_id, subtype, text, choice_a, choice_b, spice) VALUES
('freaky', 'this_or_that', 'Soft strokes or rough thrusts?', 'Soft strokes', 'Rough thrusts', 'spicy'),
('freaky', 'this_or_that', 'Naked cuddles or quickies in public?', 'Naked cuddles', 'Quickies in public', 'spicy'),
('freaky', 'this_or_that', 'Sensual massage or quick oral?', 'Sensual massage', 'Quick oral', 'spicy'),
('freaky', 'this_or_that', 'Slow undressing or ripped clothes?', 'Slow undressing', 'Ripped clothes', 'spicy'),
('freaky', 'this_or_that', 'Quiet moans or loud screams?', 'Quiet moans', 'Loud screams', 'spicy'),
('freaky', 'this_or_that', 'Watching a movie then making out or making out then watching a movie?', 'Movie then making out', 'Making out then movie', 'standard'),
('freaky', 'this_or_that', 'Dominant or submissive tonight?', 'Dominant', 'Submissive', 'spicy'),
('freaky', 'this_or_that', 'Blindfold or handcuffs?', 'Blindfold', 'Handcuffs', 'spicy'),
('freaky', 'this_or_that', 'Morning wood or night cap?', 'Morning wood', 'Night cap', 'standard'),
('freaky', 'this_or_that', 'Shower sex or bath tub soak?', 'Shower sex', 'Bath tub soak', 'spicy'),
('freaky', 'this_or_that', 'Kissing my neck or biting my lip?', 'Kissing neck', 'Biting lip', 'standard'),
('freaky', 'this_or_that', 'Quickie before work or all-nighter after drinks?', 'Quickie before work', 'All-nighter after drinks', 'spicy'),
('freaky', 'this_or_that', 'Dirty talking or silent eye contact?', 'Dirty talking', 'Silent eye contact', 'spicy'),
('freaky', 'this_or_that', 'Sneaking out of the house or staying in bed all day?', 'Sneaking out', 'Staying in bed', 'standard'),
('freaky', 'this_or_that', 'Giving or receiving oral?', 'Giving oral', 'Receiving oral', 'spicy'),
('freaky', 'this_or_that', 'Spanking or choking?', 'Spanking', 'Choking', 'spicy'),
('freaky', 'this_or_that', 'Tease me with your tongue or your fingers?', 'Tongue', 'Fingers', 'spicy'),
('freaky', 'this_or_that', 'Doing it with music or in silence?', 'With music', 'In silence', 'standard'),
('freaky', 'this_or_that', 'Bed or couch?', 'Bed', 'Couch', 'standard'),
('freaky', 'this_or_that', 'Candlelight or neon lights?', 'Candlelight', 'Neon lights', 'standard'),
('freaky', 'this_or_that', 'Toys or bare hands?', 'Toys', 'Bare hands', 'spicy'),
('freaky', 'this_or_that', 'Lingerie or completely bare?', 'Lingerie', 'Completely bare', 'spicy'),
('freaky', 'this_or_that', 'Over-the-desk or against the wall?', 'Over-the-desk', 'Against the wall', 'spicy'),
('freaky', 'this_or_that', 'Dirty texts or explicit voice notes?', 'Dirty texts', 'Explicit voice notes', 'spicy'),
('freaky', 'this_or_that', 'Mirror sex or blindfolded fantasy?', 'Mirror sex', 'Blindfolded fantasy', 'spicy'),
('freaky', 'this_or_that', 'Role playing strangers or reenacting a favorite scene?', 'Role playing strangers', 'Reenacting favorite scene', 'spicy'),
('freaky', 'this_or_that', 'Quick foreplay or extended build-up?', 'Quick foreplay', 'Extended build-up', 'standard'),
('freaky', 'this_or_that', 'Being watched or watching ourselves on video?', 'Being watched', 'Watching on video', 'spicy'),
('freaky', 'this_or_that', 'Public risk or private security?', 'Public risk', 'Private security', 'spicy'),
('freaky', 'this_or_that', 'Hot wax or ice cubes?', 'Hot wax', 'Ice cubes', 'spicy'),
('freaky', 'this_or_that', 'On top or on the bottom?', 'On top', 'On the bottom', 'standard'),
('freaky', 'this_or_that', 'Edging or immediate release?', 'Edging', 'Immediate release', 'spicy'),
('freaky', 'this_or_that', 'All fours or missionary?', 'All fours', 'Missionary', 'spicy'),
('freaky', 'this_or_that', 'Spontaneous or meticulously planned?', 'Spontaneous', 'Meticulously planned', 'standard'),
('freaky', 'this_or_that', 'Body oil or whipped cream?', 'Body oil', 'Whipped cream', 'spicy'),
('freaky', 'this_or_that', 'Sexy lingerie on or off?', 'On', 'Off', 'spicy'),
('freaky', 'this_or_that', 'Foot rub or foot focus?', 'Foot rub', 'Foot focus', 'standard'),
('freaky', 'this_or_that', 'Dirty dancing or sexy photo shoot?', 'Dirty dancing', 'Sexy photo shoot', 'spicy'),
('freaky', 'this_or_that', 'Following rules or pushing limits?', 'Following rules', 'Pushing limits', 'spicy'),
('freaky', 'this_or_that', 'Quick kisses or slow licking?', 'Quick kisses', 'Slow licking', 'spicy'),
('freaky', 'this_or_that', 'Being tied up or doing the tying?', 'Being tied up', 'Doing the tying', 'spicy'),
('freaky', 'this_or_that', 'Talk through the fantasy or act it out with no words?', 'Talk through fantasy', 'Act with no words', 'spicy'),
('freaky', 'this_or_that', 'Lingerie reveal or surprise naked?', 'Lingerie reveal', 'Surprise naked', 'spicy'),
('freaky', 'this_or_that', 'Bathroom quickie or closet quickie?', 'Bathroom quickie', 'Closet quickie', 'spicy'),
('freaky', 'this_or_that', 'Scented candles or essential oils?', 'Scented candles', 'Essential oils', 'standard'),
('freaky', 'this_or_that', 'Swapping control or establishing a single dominant?', 'Swapping control', 'Single dominant', 'spicy'),
('freaky', 'this_or_that', 'Seducing me in public or surprising me at home?', 'Seducing in public', 'Surprising at home', 'spicy'),
('freaky', 'this_or_that', 'Sexy truth or dirty dare?', 'Sexy truth', 'Dirty dare', 'spicy'),
('freaky', 'this_or_that', 'Wearing my shirt or nothing at all?', 'Wearing shirt', 'Nothing at all', 'standard'),
('freaky', 'this_or_that', 'Gaze locked or eyes closed?', 'Gaze locked', 'Eyes closed', 'standard'),
('freaky', 'this_or_that', 'Music playlist curated or natural noises?', 'Music playlist', 'Natural noises', 'standard'),
('freaky', 'this_or_that', 'Naughty selfie or full-on video?', 'Naughty selfie', 'Full-on video', 'spicy'),
('freaky', 'this_or_that', 'Clothes on halfway or totally off?', 'Halfway', 'Totally off', 'spicy'),
('freaky', 'this_or_that', 'Bathing together or showering separately then meeting?', 'Bathing together', 'Showering separately', 'standard'),
('freaky', 'this_or_that', 'High heels on or barefoot?', 'High heels on', 'Barefoot', 'standard'),
('freaky', 'this_or_that', 'Flogging or feathers?', 'Flogging', 'Feathers', 'spicy'),
('freaky', 'this_or_that', 'Leather or lace?', 'Leather', 'Lace', 'spicy'),
('freaky', 'this_or_that', 'Body shots off you or off me?', 'Off you', 'Off me', 'spicy'),
('freaky', 'this_or_that', 'Oral first or penetration first?', 'Oral first', 'Penetration first', 'spicy'),
('freaky', 'this_or_that', 'Text me fantasies or whisper them?', 'Text fantasies', 'Whisper them', 'spicy'),
('freaky', 'this_or_that', 'Full body massage or focus on one area?', 'Full body', 'Focus one area', 'standard'),
('freaky', 'this_or_that', 'Sleep naked or lingerie at bedtime?', 'Sleep naked', 'Lingerie at bedtime', 'standard'),
('freaky', 'this_or_that', 'Sex in nature or in a fancy hotel?', 'In nature', 'Fancy hotel', 'spicy'),
('freaky', 'this_or_that', 'Candle wax play or ice cube play?', 'Candle wax', 'Ice cube', 'spicy'),
('freaky', 'this_or_that', 'Rough talk or sweet talk?', 'Rough talk', 'Sweet talk', 'standard'),
('freaky', 'this_or_that', 'Breathing heavy or controlling breath?', 'Breathing heavy', 'Controlling breath', 'spicy'),
('freaky', 'this_or_that', 'Quickie before a social event or after?', 'Before', 'After', 'spicy'),
('freaky', 'this_or_that', 'Floor or bed?', 'Floor', 'Bed', 'standard'),
('freaky', 'this_or_that', 'Strip tease or lap dance?', 'Strip tease', 'Lap dance', 'spicy'),
('freaky', 'this_or_that', 'Makeup on or off during sex?', 'Makeup on', 'Off', 'standard'),
('freaky', 'this_or_that', 'Taking pictures or writing about sex?', 'Taking pictures', 'Writing about it', 'spicy'),
('freaky', 'this_or_that', 'Being pursued or doing the chasing?', 'Being pursued', 'Doing the chasing', 'standard'),
('freaky', 'this_or_that', 'Doing it in front of a mirror or via video call?', 'In front of mirror', 'Via video call', 'spicy'),
('freaky', 'this_or_that', 'Using lube or natural only?', 'Using lube', 'Natural only', 'standard'),
('freaky', 'this_or_that', 'Biting gently or scratching deeply?', 'Biting gently', 'Scratching deeply', 'spicy');

-- Insert Freaky Deck - Open Ended (75 cards)
INSERT INTO public.cards (deck_id, subtype, text, spice) VALUES
('freaky', 'open_ended', 'Describe your ultimate fantasy that we haven''t explored yet.', 'spicy'),
('freaky', 'open_ended', 'What type of touch drives you wild every time?', 'spicy'),
('freaky', 'open_ended', 'What''s one thing you want me to whisper in your ear during sex?', 'spicy'),
('freaky', 'open_ended', 'How do you feel about trying light bondage?', 'spicy'),
('freaky', 'open_ended', 'What do you fantasize about when you''re turned on by me?', 'spicy'),
('freaky', 'open_ended', 'How do you want to feel right after we finish?', 'standard'),
('freaky', 'open_ended', 'What''s your favorite sound I make when I''m turned on?', 'standard'),
('freaky', 'open_ended', 'What''s your number one turn-on about me that isn''t obvious?', 'standard'),
('freaky', 'open_ended', 'Tell me about a time you felt truly desired.', 'standard'),
('freaky', 'open_ended', 'What''s your favorite way for me to initiate intimacy?', 'standard'),
('freaky', 'open_ended', 'What kind of lingerie or outfit would you love to see me in?', 'spicy'),
('freaky', 'open_ended', 'How do you imagine our perfect sensual date night?', 'standard'),
('freaky', 'open_ended', 'What''s one thing you think would bring us closer sexually?', 'standard'),
('freaky', 'open_ended', 'What''s a secret spot on your body that I haven''t explored enough?', 'spicy'),
('freaky', 'open_ended', 'How does our chemistry compare to your past experiences?', 'standard'),
('freaky', 'open_ended', 'When do you feel the most confident and sexy?', 'standard'),
('freaky', 'open_ended', 'What words turn you on the most?', 'spicy'),
('freaky', 'open_ended', 'What scent or smell gets you in the mood instantly?', 'standard'),
('freaky', 'open_ended', 'What time of day do you like having sex the most and why?', 'standard'),
('freaky', 'open_ended', 'Describe a fantasy scenario that includes us using a toy.', 'spicy'),
('freaky', 'open_ended', 'What''s your view on incorporating food into our sex life?', 'spicy'),
('freaky', 'open_ended', 'What does dominance mean to you in the bedroom?', 'spicy'),
('freaky', 'open_ended', 'How would you react if I took complete control?', 'spicy'),
('freaky', 'open_ended', 'Do you prefer planning our sexual encounters or letting them happen spontaneously?', 'standard'),
('freaky', 'open_ended', 'How would you feel about exploring a public risk fantasy?', 'spicy'),
('freaky', 'open_ended', 'What is your favorite memory of us being intimate?', 'standard'),
('freaky', 'open_ended', 'What kind of dirty talk do you want to hear more of?', 'spicy'),
('freaky', 'open_ended', 'How do you feel about making a sex tape together?', 'spicy'),
('freaky', 'open_ended', 'When you fantasize about me, what am I doing to you?', 'spicy'),
('freaky', 'open_ended', 'How would you describe your ideal foreplay sequence?', 'standard'),
('freaky', 'open_ended', 'What is one boundary you never want to cross in our intimate life?', 'standard'),
('freaky', 'open_ended', 'Are there any fetishes or kinks you''re curious to explore?', 'spicy'),
('freaky', 'open_ended', 'How comfortable are you with me being in control?', 'spicy'),
('freaky', 'open_ended', 'How do you want to be kissed when things get heated?', 'standard'),
('freaky', 'open_ended', 'How do you like me to communicate what I want during sex?', 'standard'),
('freaky', 'open_ended', 'What does intimacy mean to you outside of sex?', 'standard'),
('freaky', 'open_ended', 'How would you feel about attending a sex club just to watch?', 'spicy'),
('freaky', 'open_ended', 'Would you rather always start with me on top or bottom? Why?', 'spicy'),
('freaky', 'open_ended', 'What is one thing we do now that you never imagined you''d enjoy?', 'standard'),
('freaky', 'open_ended', 'Describe a moment when you felt completely surrendered to me.', 'spicy'),
('freaky', 'open_ended', 'How would you rate our current sex life? What would elevate it?', 'standard'),
('freaky', 'open_ended', 'What''s a position we''ve never tried that you want to attempt?', 'spicy'),
('freaky', 'open_ended', 'How do you want me to handle you when you''re feeling submissive?', 'spicy'),
('freaky', 'open_ended', 'How do you want to handle me when you''re feeling dominant?', 'spicy'),
('freaky', 'open_ended', 'What''s one location on your sexual bucket list?', 'spicy'),
('freaky', 'open_ended', 'Describe a dream you had about us being intimate.', 'spicy'),
('freaky', 'open_ended', 'How do you feel about me using toys on you?', 'spicy'),
('freaky', 'open_ended', 'How do you feel about using restraints?', 'spicy'),
('freaky', 'open_ended', 'What is one sensory element (light, sound, touch) that enhances your arousal?', 'standard'),
('freaky', 'open_ended', 'How do you want to feel the next morning after a wild night?', 'standard'),
('freaky', 'open_ended', 'What is your favorite part of my body to explore?', 'standard'),
('freaky', 'open_ended', 'What kind of surprise would excite you most: a strip tease, a new outfit, or a risky encounter?', 'spicy'),
('freaky', 'open_ended', 'How would you describe the energy you want in bed: passionate, playful, primal, or something else?', 'standard'),
('freaky', 'open_ended', 'What does the term "making love" mean to you compared to "having sex"?', 'standard'),
('freaky', 'open_ended', 'What would an all-day marathon in bed look like for you?', 'spicy'),
('freaky', 'open_ended', 'If I wrote a love letter describing our intimacy, what would be the headline?', 'standard'),
('freaky', 'open_ended', 'How do you feel about erotic stories or reading them together?', 'spicy'),
('freaky', 'open_ended', 'What''s a small action during the day that could signal you want me later?', 'standard'),
('freaky', 'open_ended', 'How would you react if I gave you a safe word to use with me?', 'spicy'),
('freaky', 'open_ended', 'What is one thing you would love me to do in public to hint at our connection?', 'standard'),
('freaky', 'open_ended', 'How do you feel about exploring our limits together gradually?', 'spicy'),
('freaky', 'open_ended', 'If we could design the perfect playlist for us, what kind of songs would be on it?', 'standard'),
('freaky', 'open_ended', 'What is something small during sex that always makes you feel loved?', 'standard'),
('freaky', 'open_ended', 'How do you want to celebrate after we try something new?', 'standard'),
('freaky', 'open_ended', 'If you could write the script for a night in, how would it go?', 'spicy'),
('freaky', 'open_ended', 'What is one toy or accessory you would like to try with me?', 'spicy'),
('freaky', 'open_ended', 'How do you feel about me directing you with my hands or words?', 'spicy'),
('freaky', 'open_ended', 'How do you want to be surprised after a long day to get you in the mood?', 'standard'),
('freaky', 'open_ended', 'What is the best compliment I can give you in the bedroom?', 'standard'),
('freaky', 'open_ended', 'If you could pick a location anywhere in the world for us to be intimate, where would it be?', 'standard'),
('freaky', 'open_ended', 'How do you envision our sexual connection evolving over the years?', 'standard'),
('freaky', 'open_ended', 'What would you love me to explore that we haven''t thought about yet?', 'spicy'),
('freaky', 'open_ended', 'How do you want me to care for you after an intense session?', 'standard'),
('freaky', 'open_ended', 'What does vulnerability look like to you in our intimacy?', 'standard'),
('freaky', 'open_ended', 'What are you afraid to tell me but want to share about your desires?', 'spicy');

-- Insert Freaky Deck - Say Sip Strip (50 cards)
INSERT INTO public.cards (deck_id, subtype, text, spice) VALUES
('freaky', 'say_sip_strip', 'Share the wildest place you''ve ever had sex. If you don''t, sip or strip.', 'spicy'),
('freaky', 'say_sip_strip', 'What''s your favorite word to hear me say when I''m taking control? Say it or strip.', 'spicy'),
('freaky', 'say_sip_strip', 'Confess a secret fantasy involving me that you''ve never said aloud. Sip if you can''t.', 'spicy'),
('freaky', 'say_sip_strip', 'Describe your craziest orgasm in detail. If that''s too much, take off something.', 'spicy'),
('freaky', 'say_sip_strip', 'Tell me what part of my body you would lick forever. If you refuse, drink.', 'spicy'),
('freaky', 'say_sip_strip', 'Admit the last time you fantasized about me while alone. If that''s too private, strip.', 'spicy'),
('freaky', 'say_sip_strip', 'Ask me to do something to you right now, or take a sip.', 'spicy'),
('freaky', 'say_sip_strip', 'Reveal your favorite porn category. Or remove an item.', 'spicy'),
('freaky', 'say_sip_strip', 'Tell the truth: have you ever faked an orgasm with me? If you lie, drink.', 'spicy'),
('freaky', 'say_sip_strip', 'Name a sexual act you think about but haven''t tried. If you won''t, strip.', 'spicy'),
('freaky', 'say_sip_strip', 'How would you feel about a threesome with a stranger? Sip or strip if you won''t answer.', 'spicy'),
('freaky', 'say_sip_strip', 'What song makes you think about sex with me? Sing it, sip or strip.', 'spicy'),
('freaky', 'say_sip_strip', 'Describe how you want me to take control in one sentence. If you can''t, drink.', 'spicy'),
('freaky', 'say_sip_strip', 'Share a sexy dream you''ve had about us. If you don''t remember, remove something.', 'spicy'),
('freaky', 'say_sip_strip', 'Tell me where you''d want me to kiss you right now. If you won''t, sip.', 'spicy'),
('freaky', 'say_sip_strip', 'What''s the weirdest thing that turns you on? Reveal or strip.', 'spicy'),
('freaky', 'say_sip_strip', 'Whisper something dirty in my ear. Or sip.', 'spicy'),
('freaky', 'say_sip_strip', 'Admit a toy you want to buy for us. Or remove something.', 'spicy'),
('freaky', 'say_sip_strip', 'Tell me if you''d let me blindfold you tonight. If you won''t answer, drink.', 'spicy'),
('freaky', 'say_sip_strip', 'How would you feel about filming us? Answer or strip.', 'spicy'),
('freaky', 'say_sip_strip', 'Reveal a public place you''ve fantasized about doing it. Or take a sip.', 'spicy'),
('freaky', 'say_sip_strip', 'Give me your kink rating from 1–10. If you won''t, strip.', 'spicy'),
('freaky', 'say_sip_strip', 'Tell me one thing I do in bed that you wish I''d do more. Or sip.', 'spicy'),
('freaky', 'say_sip_strip', 'Reveal whether you''d watch me with someone else. Or drink.', 'spicy'),
('freaky', 'say_sip_strip', 'Admit if you''d want to see me with another woman or man. Or strip.', 'spicy'),
('freaky', 'say_sip_strip', 'Tell me your safe word. If you don''t have one, make one up or sip.', 'spicy'),
('freaky', 'say_sip_strip', 'Describe your perfect quickie scenario. If you can''t, remove something.', 'spicy'),
('freaky', 'say_sip_strip', 'Admit if you like biting or being bitten more. Or sip.', 'spicy'),
('freaky', 'say_sip_strip', 'Tell me your favorite time we made love. If you can''t recall, strip.', 'standard'),
('freaky', 'say_sip_strip', 'Make up a new nickname for my favorite body part. Or take a sip.', 'standard'),
('freaky', 'say_sip_strip', 'Tell me if you''d let me tie you up. If you won''t answer, strip.', 'spicy'),
('freaky', 'say_sip_strip', 'Admit a sexual experience you''ve had that you''d never repeat. Or drink.', 'spicy'),
('freaky', 'say_sip_strip', 'Reveal something you want to hear during sex. Or strip.', 'spicy'),
('freaky', 'say_sip_strip', 'Tell me the dirtiest thing you''ve texted me. If you won''t, sip.', 'spicy'),
('freaky', 'say_sip_strip', 'Admit if you''d ever consider an open relationship. Or remove something.', 'spicy'),
('freaky', 'say_sip_strip', 'Describe what "tease" means to you. If you can''t, drink.', 'standard'),
('freaky', 'say_sip_strip', 'Tell me if you''ve ever had a crush on a friend''s partner. Or strip.', 'standard'),
('freaky', 'say_sip_strip', 'Admit if you''ve sent a nude to someone else after we got together. Or sip.', 'spicy'),
('freaky', 'say_sip_strip', 'Tell me what you''d write in a note on my body for me to find later. Or remove something.', 'spicy'),
('freaky', 'say_sip_strip', 'Admit if you''d roleplay a taboo scenario with me. If no answer, drink.', 'spicy'),
('freaky', 'say_sip_strip', 'Reveal something that instantly turns you off. Or strip.', 'standard'),
('freaky', 'say_sip_strip', 'Tell me the last time you touched yourself thinking of me. Or sip.', 'spicy'),
('freaky', 'say_sip_strip', 'Admit if you''ve ever thought about someone else during sex with me. Or strip.', 'spicy'),
('freaky', 'say_sip_strip', 'Reveal what you''d like to be called when being dominated. Or sip.', 'spicy'),
('freaky', 'say_sip_strip', 'Describe in detail how you like your oral. Or remove something.', 'spicy'),
('freaky', 'say_sip_strip', 'Tell me if you''d be into pegging or trying it. If you won''t answer, drink.', 'spicy'),
('freaky', 'say_sip_strip', 'Name a sex position you love but we seldom do. Or strip.', 'spicy'),
('freaky', 'say_sip_strip', 'Confess if you''d let me spank you in front of someone else. Or sip.', 'spicy'),
('freaky', 'say_sip_strip', 'Tell me where you''d want to be kissed for hours. Or remove something.', 'spicy'),
('freaky', 'say_sip_strip', 'Reveal if you''d want me to mark you with a hickey somewhere visible. Or drink.', 'standard');

-- Insert Real Talk Deck - This or That (75 cards)
INSERT INTO public.cards (deck_id, subtype, text, choice_a, choice_b, spice) VALUES
('real_talk', 'this_or_that', 'Talk it out immediately or process alone first?', 'Talk immediately', 'Process alone first', 'standard'),
('real_talk', 'this_or_that', 'Honesty that hurts or comfort that hides?', 'Honesty that hurts', 'Comfort that hides', 'standard'),
('real_talk', 'this_or_that', 'Trust or respect?', 'Trust', 'Respect', 'standard'),
('real_talk', 'this_or_that', 'Save money or spend on experiences?', 'Save money', 'Spend on experiences', 'soft'),
('real_talk', 'this_or_that', 'Apologize with words or actions?', 'With words', 'With actions', 'standard'),
('real_talk', 'this_or_that', 'Speak your mind or keep peace?', 'Speak your mind', 'Keep peace', 'standard'),
('real_talk', 'this_or_that', 'Work to live or live to work?', 'Work to live', 'Live to work', 'soft'),
('real_talk', 'this_or_that', 'Set boundaries early or adjust them later?', 'Set early', 'Adjust later', 'standard'),
('real_talk', 'this_or_that', 'Love languages: words of affirmation or acts of service?', 'Words of affirmation', 'Acts of service', 'soft'),
('real_talk', 'this_or_that', 'Date nights in or nights out?', 'Nights in', 'Nights out', 'soft'),
('real_talk', 'this_or_that', 'Forgiveness or moving on?', 'Forgiveness', 'Moving on', 'standard'),
('real_talk', 'this_or_that', 'Passionate arguments or calm discussions?', 'Passionate arguments', 'Calm discussions', 'standard'),
('real_talk', 'this_or_that', 'Texting or calling for serious conversations?', 'Texting', 'Calling', 'soft'),
('real_talk', 'this_or_that', 'Plan spontaneously or schedule ahead?', 'Plan spontaneously', 'Schedule ahead', 'soft'),
('real_talk', 'this_or_that', 'Truth or dare when talking about feelings?', 'Truth', 'Dare', 'soft'),
('real_talk', 'this_or_that', 'Quality time or quality gifts?', 'Quality time', 'Quality gifts', 'soft'),
('real_talk', 'this_or_that', 'Routine or adventure?', 'Routine', 'Adventure', 'soft'),
('real_talk', 'this_or_that', 'Tradition or change?', 'Tradition', 'Change', 'standard'),
('real_talk', 'this_or_that', 'Compromise or stand your ground?', 'Compromise', 'Stand your ground', 'standard'),
('real_talk', 'this_or_that', 'Open to feedback or protective of feelings?', 'Open to feedback', 'Protective of feelings', 'standard'),
('real_talk', 'this_or_that', 'Sleeping angry or staying up to hash it out?', 'Sleeping angry', 'Hash it out', 'standard'),
('real_talk', 'this_or_that', 'Long-term goals or present moment focus?', 'Long-term goals', 'Present moment', 'soft'),
('real_talk', 'this_or_that', 'Partner''s family or chosen family?', 'Partner''s family', 'Chosen family', 'standard'),
('real_talk', 'this_or_that', 'Staying quiet or speaking up in public?', 'Staying quiet', 'Speaking up', 'standard'),
('real_talk', 'this_or_that', 'Doing chores together or dividing them?', 'Together', 'Dividing them', 'soft'),
('real_talk', 'this_or_that', 'Intuition or logic when making decisions?', 'Intuition', 'Logic', 'soft'),
('real_talk', 'this_or_that', 'Giving advice or simply listening?', 'Giving advice', 'Simply listening', 'soft'),
('real_talk', 'this_or_that', 'Celebrating milestones big or small?', 'Big', 'Small', 'soft'),
('real_talk', 'this_or_that', 'High emotional intensity or consistent stability?', 'High intensity', 'Consistent stability', 'standard'),
('real_talk', 'this_or_that', 'Being right or being heard?', 'Being right', 'Being heard', 'standard'),
('real_talk', 'this_or_that', 'Leading or following in a relationship?', 'Leading', 'Following', 'standard'),
('real_talk', 'this_or_that', 'Love or lust to start a relationship?', 'Love', 'Lust', 'standard'),
('real_talk', 'this_or_that', 'Taking breaks in conflicts or resolving right away?', 'Taking breaks', 'Resolving right away', 'standard'),
('real_talk', 'this_or_that', 'Private apologies or public accountability?', 'Private apologies', 'Public accountability', 'standard'),
('real_talk', 'this_or_that', 'Financial security or career satisfaction?', 'Financial security', 'Career satisfaction', 'soft'),
('real_talk', 'this_or_that', 'Upfront about expectations or letting things flow?', 'Upfront', 'Letting things flow', 'standard'),
('real_talk', 'this_or_that', 'Same page or agree to disagree?', 'Same page', 'Agree to disagree', 'standard'),
('real_talk', 'this_or_that', 'Emotional vulnerability or emotional resilience?', 'Vulnerability', 'Resilience', 'standard'),
('real_talk', 'this_or_that', 'Being challenged or supported?', 'Challenged', 'Supported', 'standard'),
('real_talk', 'this_or_that', 'Freedom or commitment?', 'Freedom', 'Commitment', 'standard'),
('real_talk', 'this_or_that', 'Spontaneous travel or carefully planned trips?', 'Spontaneous', 'Carefully planned', 'soft'),
('real_talk', 'this_or_that', 'Children or no children?', 'Children', 'No children', 'standard'),
('real_talk', 'this_or_that', 'Public affection or private affection?', 'Public', 'Private', 'soft'),
('real_talk', 'this_or_that', 'Joint social media accounts or separate?', 'Joint', 'Separate', 'soft'),
('real_talk', 'this_or_that', 'Shared bank accounts or separate finances?', 'Shared', 'Separate', 'standard'),
('real_talk', 'this_or_that', 'Arguing in front of kids or behind closed doors?', 'In front of kids', 'Behind closed doors', 'standard'),
('real_talk', 'this_or_that', 'Therapy or self-help books?', 'Therapy', 'Self-help books', 'standard'),
('real_talk', 'this_or_that', 'Social activism or personal growth focus?', 'Social activism', 'Personal growth', 'soft'),
('real_talk', 'this_or_that', 'Early riser or night owl partner?', 'Early riser', 'Night owl', 'soft'),
('real_talk', 'this_or_that', 'Big wedding or elopement?', 'Big wedding', 'Elopement', 'soft'),
('real_talk', 'this_or_that', 'Pets or no pets?', 'Pets', 'No pets', 'soft'),
('real_talk', 'this_or_that', 'City life or suburban life?', 'City life', 'Suburban life', 'soft'),
('real_talk', 'this_or_that', 'Minimalism or abundance?', 'Minimalism', 'Abundance', 'soft'),
('real_talk', 'this_or_that', 'Clean as you go or deep clean day?', 'Clean as you go', 'Deep clean day', 'soft'),
('real_talk', 'this_or_that', 'Home-cooked meals or dining out?', 'Home-cooked', 'Dining out', 'soft'),
('real_talk', 'this_or_that', 'Daily check-ins or weekly catch-ups?', 'Daily check-ins', 'Weekly catch-ups', 'soft'),
('real_talk', 'this_or_that', 'Career ambition or life balance?', 'Career ambition', 'Life balance', 'standard'),
('real_talk', 'this_or_that', 'Health focus: mental or physical?', 'Mental', 'Physical', 'soft'),
('real_talk', 'this_or_that', 'Romantic gestures: grand or subtle?', 'Grand', 'Subtle', 'soft'),
('real_talk', 'this_or_that', 'Marriage or long-term partnership without marriage?', 'Marriage', 'Partnership without marriage', 'standard'),
('real_talk', 'this_or_that', 'Individual hobbies or shared hobbies?', 'Individual', 'Shared', 'soft'),
('real_talk', 'this_or_that', 'Getting advice from friends or professional counselor?', 'Friends', 'Professional counselor', 'standard'),
('real_talk', 'this_or_that', 'Vacation: relax or explore?', 'Relax', 'Explore', 'soft'),
('real_talk', 'this_or_that', 'Surprising partner or being surprised?', 'Surprising', 'Being surprised', 'soft'),
('real_talk', 'this_or_that', 'Technology: connected or unplugged time?', 'Connected', 'Unplugged', 'soft'),
('real_talk', 'this_or_that', 'Celebrating birthdays or indifferent?', 'Celebrating', 'Indifferent', 'soft'),
('real_talk', 'this_or_that', 'Personal space or constant closeness?', 'Personal space', 'Constant closeness', 'standard'),
('real_talk', 'this_or_that', 'Making major decisions together or individually then consult?', 'Together', 'Individually then consult', 'standard'),
('real_talk', 'this_or_that', 'Age gap: older or younger partner?', 'Older', 'Younger', 'soft'),
('real_talk', 'this_or_that', 'Expressing affection privately or publicly?', 'Privately', 'Publicly', 'soft'),
('real_talk', 'this_or_that', 'Family first or partner first?', 'Family first', 'Partner first', 'standard'),
('real_talk', 'this_or_that', 'Spontaneous gifts or planned ones?', 'Spontaneous', 'Planned', 'soft'),
('real_talk', 'this_or_that', 'Live near relatives or far away?', 'Near relatives', 'Far away', 'soft'),
('real_talk', 'this_or_that', 'Teamwork or independence?', 'Teamwork', 'Independence', 'standard'),
('real_talk', 'this_or_that', 'Life motto: YOLO or plan ahead?', 'YOLO', 'Plan ahead', 'soft');

-- Due to character limits, I'll continue the Real Talk and Love Drunk cards in the next part of the migration
-- Insert Real Talk Deck - Open Ended (75 cards)
INSERT INTO public.cards (deck_id, subtype, text, spice) VALUES
('real_talk', 'open_ended', 'What are three nonnegotiable values you want in a relationship?', 'standard'),
('real_talk', 'open_ended', 'How do you prefer to be approached when I need to address an issue with you?', 'standard'),
('real_talk', 'open_ended', 'What does a balanced relationship look like to you?', 'standard'),
('real_talk', 'open_ended', 'What did your childhood teach you about love?', 'standard'),
('real_talk', 'open_ended', 'How do you want to be supported when you''re stressed?', 'soft'),
('real_talk', 'open_ended', 'What role do you think friends should play in a relationship?', 'standard'),
('real_talk', 'open_ended', 'When do you feel the most loved by me?', 'soft'),
('real_talk', 'open_ended', 'How do you define emotional safety?', 'standard'),
('real_talk', 'open_ended', 'What''s one thing you admire about the way your parents'' relationship works or doesn''t?', 'standard'),
('real_talk', 'open_ended', 'What are your financial goals for us as a couple?', 'standard'),
('real_talk', 'open_ended', 'How do you feel about therapy and growth?', 'standard'),
('real_talk', 'open_ended', 'What does compromise mean to you?', 'standard'),
('real_talk', 'open_ended', 'How do you handle feeling jealous?', 'standard'),
('real_talk', 'open_ended', 'What''s your biggest fear about long-term commitment?', 'standard'),
('real_talk', 'open_ended', 'How do you feel about gender roles?', 'standard'),
('real_talk', 'open_ended', 'What are the habits you think could improve our relationship?', 'standard'),
('real_talk', 'open_ended', 'How do you want to celebrate milestones as a couple?', 'soft'),
('real_talk', 'open_ended', 'When do you feel like your voice isn''t being heard?', 'standard'),
('real_talk', 'open_ended', 'How do you handle being wrong in an argument?', 'standard'),
('real_talk', 'open_ended', 'What does accountability look like to you?', 'standard'),
('real_talk', 'open_ended', 'How do you handle stress and how can I help?', 'soft'),
('real_talk', 'open_ended', 'What does self-care mean for you?', 'soft'),
('real_talk', 'open_ended', 'How do you like to receive apologies?', 'standard'),
('real_talk', 'open_ended', 'How do you feel about keeping separate hobbies?', 'soft'),
('real_talk', 'open_ended', 'What''s one tradition you''d like to start with me?', 'soft'),
('real_talk', 'open_ended', 'What do you need when you''re feeling insecure?', 'standard'),
('real_talk', 'open_ended', 'How do you see our roles in raising kids if we had them?', 'standard'),
('real_talk', 'open_ended', 'What''s a conflict style you appreciate in other couples?', 'standard'),
('real_talk', 'open_ended', 'When have you felt most misunderstood by me?', 'standard'),
('real_talk', 'open_ended', 'What is a life philosophy you live by?', 'soft'),
('real_talk', 'open_ended', 'How do you feel about sharing passwords or digital privacy?', 'standard'),
('real_talk', 'open_ended', 'What does loyalty mean to you?', 'standard'),
('real_talk', 'open_ended', 'How can we better support each other''s personal goals?', 'soft'),
('real_talk', 'open_ended', 'What kind of legacy do you want to leave?', 'soft'),
('real_talk', 'open_ended', 'What does forgiveness look like to you?', 'standard'),
('real_talk', 'open_ended', 'How do you handle envy towards other couples'' lives?', 'standard'),
('real_talk', 'open_ended', 'When has your pride gotten in the way of our relationship?', 'standard'),
('real_talk', 'open_ended', 'What boundaries do you need to feel safe?', 'standard'),
('real_talk', 'open_ended', 'How can I be a better listener for you?', 'soft'),
('real_talk', 'open_ended', 'How should we handle disagreements about money?', 'standard'),
('real_talk', 'open_ended', 'What do you think is the biggest challenge facing our generation''s relationships?', 'standard'),
('real_talk', 'open_ended', 'What traditions from your family do you want to carry forward?', 'soft'),
('real_talk', 'open_ended', 'How do you envision our lives in five years?', 'soft'),
('real_talk', 'open_ended', 'When do you feel most connected to me?', 'soft'),
('real_talk', 'open_ended', 'How do you handle feeling overwhelmed by life?', 'standard'),
('real_talk', 'open_ended', 'What does vulnerability look like for you?', 'standard'),
('real_talk', 'open_ended', 'How can we make our home a sanctuary for both of us?', 'soft'),
('real_talk', 'open_ended', 'When you think of our future, what excites you?', 'soft'),
('real_talk', 'open_ended', 'How do you handle disagreements about extended family?', 'standard'),
('real_talk', 'open_ended', 'What''s your love language and how can I speak it better?', 'soft'),
('real_talk', 'open_ended', 'What would you do if we hit a major disagreement that felt unsolvable?', 'standard'),
('real_talk', 'open_ended', 'How do you feel about sharing finances?', 'standard'),
('real_talk', 'open_ended', 'How do you decide when to voice your needs?', 'standard'),
('real_talk', 'open_ended', 'What''s a dream we should pursue together?', 'soft'),
('real_talk', 'open_ended', 'What do you need from me when you''re feeling depressed?', 'standard'),
('real_talk', 'open_ended', 'How do you want to handle disagreements in front of children?', 'standard'),
('real_talk', 'open_ended', 'What time do you need for yourself each week?', 'soft'),
('real_talk', 'open_ended', 'What are your thoughts on prenuptial agreements?', 'standard'),
('real_talk', 'open_ended', 'How do you feel about my closest friends?', 'standard'),
('real_talk', 'open_ended', 'What do you want me to do more of in our daily routine?', 'soft'),
('real_talk', 'open_ended', 'When has our relationship felt easiest?', 'soft'),
('real_talk', 'open_ended', 'When has our relationship felt most strained?', 'standard'),
('real_talk', 'open_ended', 'How do you handle feeling criticized?', 'standard'),
('real_talk', 'open_ended', 'What does healthy disagreement look like for us?', 'standard'),
('real_talk', 'open_ended', 'How do you feel about religion or spirituality in our lives?', 'standard'),
('real_talk', 'open_ended', 'What do you think about moving to a new city or country?', 'soft'),
('real_talk', 'open_ended', 'How would you handle a difference in parenting styles?', 'standard'),
('real_talk', 'open_ended', 'What does quality time look like to you?', 'soft'),
('real_talk', 'open_ended', 'How do you want us to handle long-distance if that ever happened?', 'standard'),
('real_talk', 'open_ended', 'What is your biggest pet peeve in relationships?', 'standard'),
('real_talk', 'open_ended', 'What do you need to trust someone fully?', 'standard'),
('real_talk', 'open_ended', 'How do you feel about living with my family for a while?', 'standard'),
('real_talk', 'open_ended', 'What does partnership mean to you when times are tough?', 'standard'),
('real_talk', 'open_ended', 'How can we keep our individuality while being a couple?', 'standard'),
('real_talk', 'open_ended', 'What is a lesson you learned from past relationships you want to apply here?', 'standard');

-- Insert Real Talk Deck - Say Sip Strip (50 cards)
INSERT INTO public.cards (deck_id, subtype, text, spice) VALUES
('real_talk', 'say_sip_strip', 'Admit the most petty reason you ever started an argument. Sip or strip if it''s too embarrassing.', 'standard'),
('real_talk', 'say_sip_strip', 'Reveal a personal habit you know annoys me. If you won''t, drink or strip.', 'standard'),
('real_talk', 'say_sip_strip', 'Share a fear about our relationship you haven''t voiced. Or sip.', 'standard'),
('real_talk', 'say_sip_strip', 'Tell me about a time you felt insecure with me. Or strip.', 'standard'),
('real_talk', 'say_sip_strip', 'Be honest: have you kept a secret from me? If so, share it or drink.', 'standard'),
('real_talk', 'say_sip_strip', 'Confess a past mistake in love you haven''t owned up to. Or remove something.', 'standard'),
('real_talk', 'say_sip_strip', 'Share a time you didn''t feel supported by me. Or sip.', 'standard'),
('real_talk', 'say_sip_strip', 'Admit a problem you still hold onto from your childhood. Or strip.', 'standard'),
('real_talk', 'say_sip_strip', 'Reveal a value we clash on. Or drink.', 'standard'),
('real_talk', 'say_sip_strip', 'Tell me something you would change about me if you could. Or take off something.', 'standard'),
('real_talk', 'say_sip_strip', 'Confess whether you''ve checked my phone without permission. Or sip.', 'standard'),
('real_talk', 'say_sip_strip', 'Admit if you''ve ever thought about ending us. Or strip.', 'standard'),
('real_talk', 'say_sip_strip', 'Share a belief you have that most people disagree with. Or drink.', 'standard'),
('real_talk', 'say_sip_strip', 'Name one of my friends you don''t really trust. Or remove something.', 'standard'),
('real_talk', 'say_sip_strip', 'Tell me about a time you were jealous of me. Or sip.', 'standard'),
('real_talk', 'say_sip_strip', 'Confess what you think our biggest relationship issue is. Or strip.', 'standard'),
('real_talk', 'say_sip_strip', 'Reveal the worst advice a friend has given you about us. Or drink.', 'standard'),
('real_talk', 'say_sip_strip', 'Share a secret anxiety you carry about our future. Or remove something.', 'standard'),
('real_talk', 'say_sip_strip', 'Admit if you''ve ever lied to get out of a fight. Or sip.', 'standard'),
('real_talk', 'say_sip_strip', 'Tell me a stereotype you''ve held about men or women and how it affected you. Or strip.', 'standard'),
('real_talk', 'say_sip_strip', 'Confess something you''re ashamed of that affects your relationships. Or drink.', 'standard'),
('real_talk', 'say_sip_strip', 'Reveal one trait from your parents you fear inheriting. Or remove something.', 'standard'),
('real_talk', 'say_sip_strip', 'Share a moment when you felt out of love with me. Or sip.', 'standard'),
('real_talk', 'say_sip_strip', 'Tell me how you truly feel about my family. Or strip.', 'standard'),
('real_talk', 'say_sip_strip', 'Admit if you''ve ever pretended to agree just to end a conversation. Or drink.', 'standard'),
('real_talk', 'say_sip_strip', 'Reveal something you judge others for. Or remove something.', 'standard'),
('real_talk', 'say_sip_strip', 'Confess a time you were wrong but wouldn''t admit it. Or sip.', 'standard'),
('real_talk', 'say_sip_strip', 'Share a personal failure that still hurts. Or strip.', 'standard'),
('real_talk', 'say_sip_strip', 'Tell me what you think my most toxic trait is. Or drink.', 'standard'),
('real_talk', 'say_sip_strip', 'Admit if you''ve ever compared me to an ex. Or remove something.', 'standard'),
('real_talk', 'say_sip_strip', 'Reveal something you thought about me before we dated that you now know was wrong. Or sip.', 'soft'),
('real_talk', 'say_sip_strip', 'Share an insecurity about your appearance. Or strip.', 'soft'),
('real_talk', 'say_sip_strip', 'Tell me if there''s something you resent me for. Or drink.', 'standard'),
('real_talk', 'say_sip_strip', 'Admit if you have a secret social media account. Or remove something.', 'standard'),
('real_talk', 'say_sip_strip', 'Reveal the hardest truth about yourself. Or sip.', 'standard'),
('real_talk', 'say_sip_strip', 'Confess what you think is your worst habit. Or strip.', 'standard'),
('real_talk', 'say_sip_strip', 'Share a time you lied to your parents. Or drink.', 'soft'),
('real_talk', 'say_sip_strip', 'Tell me something you''d never compromise on in our relationship. Or remove something.', 'standard'),
('real_talk', 'say_sip_strip', 'Admit the last time you felt disrespected by me. Or sip.', 'standard'),
('real_talk', 'say_sip_strip', 'Reveal if you''d want to read my messages if I offered. Or strip.', 'standard'),
('real_talk', 'say_sip_strip', 'Confess a stereotype about relationships you believed when we met. Or drink.', 'soft'),
('real_talk', 'say_sip_strip', 'Share a secret about your past that could affect our future. Or remove something.', 'standard'),
('real_talk', 'say_sip_strip', 'Tell me your biggest regret in life so far. Or sip.', 'standard'),
('real_talk', 'say_sip_strip', 'Admit if you feel envious of me in any way. Or strip.', 'standard'),
('real_talk', 'say_sip_strip', 'Reveal something you feel guilty about in this relationship. Or drink.', 'standard'),
('real_talk', 'say_sip_strip', 'Tell me the one piece of advice you would give your younger self about love. Or remove something.', 'soft'),
('real_talk', 'say_sip_strip', 'Confess if you''ve ever given someone else a flirty compliment while with me. Or sip.', 'standard'),
('real_talk', 'say_sip_strip', 'Share a time you felt like walking away from a fight with me. Or strip.', 'standard'),
('real_talk', 'say_sip_strip', 'Tell me one thing you think I''m oblivious about. Or drink.', 'standard'),
('real_talk', 'say_sip_strip', 'Reveal a belief about relationships you wish others would understand. Or remove something.', 'soft');

-- Insert Love Drunk Deck - This or That (75 cards)
INSERT INTO public.cards (deck_id, subtype, text, choice_a, choice_b, spice) VALUES
('love_drunk', 'this_or_that', 'Slow dancing or star gazing?', 'Slow dancing', 'Star gazing', 'soft'),
('love_drunk', 'this_or_that', 'Breakfast in bed or dinner under the stars?', 'Breakfast in bed', 'Dinner under stars', 'soft'),
('love_drunk', 'this_or_that', 'Public displays of affection or private love notes?', 'Public displays', 'Private love notes', 'soft'),
('love_drunk', 'this_or_that', 'Surprise trips or surprise gifts?', 'Surprise trips', 'Surprise gifts', 'soft'),
('love_drunk', 'this_or_that', 'Love letters or love playlists?', 'Love letters', 'Love playlists', 'soft'),
('love_drunk', 'this_or_that', 'Holding hands or kisses on the forehead?', 'Holding hands', 'Forehead kisses', 'soft'),
('love_drunk', 'this_or_that', 'Sharing clothes or sharing secrets?', 'Sharing clothes', 'Sharing secrets', 'soft'),
('love_drunk', 'this_or_that', 'Movie night in or fancy date night out?', 'Movie night in', 'Date night out', 'soft'),
('love_drunk', 'this_or_that', 'Cooking together or ordering in from a favorite spot?', 'Cooking together', 'Ordering in', 'soft'),
('love_drunk', 'this_or_that', 'Matching tattoos or matching outfits?', 'Matching tattoos', 'Matching outfits', 'soft'),
('love_drunk', 'this_or_that', 'Spontaneous road trip or planned vacation?', 'Spontaneous road trip', 'Planned vacation', 'soft'),
('love_drunk', 'this_or_that', 'Flowers for no reason or chocolates for no reason?', 'Flowers', 'Chocolates', 'soft'),
('love_drunk', 'this_or_that', 'Staying up talking all night or sleeping wrapped up together?', 'Talking all night', 'Sleeping together', 'soft'),
('love_drunk', 'this_or_that', 'Saying "I love you" in public or private?', 'In public', 'In private', 'soft'),
('love_drunk', 'this_or_that', 'Building traditions or living in the moment?', 'Building traditions', 'Living in moment', 'soft'),
('love_drunk', 'this_or_that', 'Photo albums or digital memories?', 'Photo albums', 'Digital memories', 'soft'),
('love_drunk', 'this_or_that', 'Surprise breakfast or surprise lunch at work?', 'Surprise breakfast', 'Surprise lunch', 'soft'),
('love_drunk', 'this_or_that', 'Long hugs or soft kisses?', 'Long hugs', 'Soft kisses', 'soft'),
('love_drunk', 'this_or_that', 'Couple''s spa day or adventure sport date?', 'Spa day', 'Adventure sport', 'soft'),
('love_drunk', 'this_or_that', 'Saying "yes" to everything for a day or planning your perfect date?', 'Saying yes to everything', 'Planning perfect date', 'soft'),
('love_drunk', 'this_or_that', 'Romantic getaway or staycation?', 'Romantic getaway', 'Staycation', 'soft'),
('love_drunk', 'this_or_that', 'Writing vows together or separately?', 'Together', 'Separately', 'standard'),
('love_drunk', 'this_or_that', 'Watching the sunrise or the sunset together?', 'Sunrise', 'Sunset', 'soft'),
('love_drunk', 'this_or_that', 'Dream home in the city or dream home in the mountains?', 'In the city', 'In the mountains', 'soft'),
('love_drunk', 'this_or_that', 'Giving compliments or receiving them?', 'Giving', 'Receiving', 'soft'),
('love_drunk', 'this_or_that', 'Creating a joint playlist or sending each other songs?', 'Joint playlist', 'Sending songs', 'soft'),
('love_drunk', 'this_or_that', 'Celebrating monthsaries or anniversaries only?', 'Monthsaries', 'Anniversaries only', 'soft'),
('love_drunk', 'this_or_that', 'Opening gifts together or surprising each other on separate days?', 'Together', 'Separate days', 'soft'),
('love_drunk', 'this_or_that', 'Personalized gifts or practical gifts?', 'Personalized', 'Practical', 'soft'),
('love_drunk', 'this_or_that', 'Candlelit dinner or picnic under the stars?', 'Candlelit dinner', 'Picnic under stars', 'soft'),
('love_drunk', 'this_or_that', 'Holding hands in public or linking arms?', 'Holding hands', 'Linking arms', 'soft'),
('love_drunk', 'this_or_that', 'Going to bed at the same time or flexible bed times?', 'Same time', 'Flexible', 'soft'),
('love_drunk', 'this_or_that', 'Dancing in the kitchen or singing in the shower together?', 'Dancing in kitchen', 'Singing in shower', 'soft'),
('love_drunk', 'this_or_that', 'Joint checking account or separate with joint savings?', 'Joint checking', 'Separate with joint', 'standard'),
('love_drunk', 'this_or_that', 'Traditional wedding or eloping somewhere secret?', 'Traditional wedding', 'Eloping', 'standard'),
('love_drunk', 'this_or_that', 'Couple tattoos or matching jewelry?', 'Couple tattoos', 'Matching jewelry', 'soft'),
('love_drunk', 'this_or_that', 'Romantic poems or romantic text messages?', 'Romantic poems', 'Text messages', 'soft'),
('love_drunk', 'this_or_that', 'Plan a future together or see where it goes?', 'Plan future', 'See where it goes', 'standard'),
('love_drunk', 'this_or_that', 'Celebrating Valentine''s Day or celebrating your own special day?', 'Valentine''s Day', 'Own special day', 'soft'),
('love_drunk', 'this_or_that', 'Surprising with a pet or surprising with a trip?', 'Surprising with pet', 'Surprising with trip', 'soft'),
('love_drunk', 'this_or_that', 'Kisses on the cheek or kisses on the neck?', 'On the cheek', 'On the neck', 'standard'),
('love_drunk', 'this_or_that', 'Matching pajamas or matching gym outfits?', 'Matching pajamas', 'Matching gym outfits', 'soft'),
('love_drunk', 'this_or_that', 'Giving up something for love or compromise together?', 'Giving up something', 'Compromise together', 'standard'),
('love_drunk', 'this_or_that', 'Building a family early or waiting longer?', 'Early', 'Waiting longer', 'standard'),
('love_drunk', 'this_or_that', 'Celebrating each other''s achievements loudly or quietly?', 'Loudly', 'Quietly', 'soft'),
('love_drunk', 'this_or_that', 'Doing little things daily or big gestures occasionally?', 'Little things daily', 'Big gestures', 'soft'),
('love_drunk', 'this_or_that', 'Celebrating with friends or just the two of you?', 'With friends', 'Just two of us', 'soft'),
('love_drunk', 'this_or_that', 'Living near family or living far away together?', 'Near family', 'Far away', 'standard'),
('love_drunk', 'this_or_that', 'Frequent mini dates or occasional big date nights?', 'Mini dates', 'Big date nights', 'soft'),
('love_drunk', 'this_or_that', 'Cuddling on the couch or exploring new restaurants?', 'Cuddling on couch', 'Exploring restaurants', 'soft'),
('love_drunk', 'this_or_that', 'Adopting a pet or having a baby first?', 'Adopting pet', 'Having baby', 'standard'),
('love_drunk', 'this_or_that', 'Dream wedding or dream honeymoon?', 'Dream wedding', 'Dream honeymoon', 'soft'),
('love_drunk', 'this_or_that', 'Money invested in experiences or saved for future?', 'Invested in experiences', 'Saved for future', 'soft'),
('love_drunk', 'this_or_that', 'Celebrating birthdays with big parties or intimate dinners?', 'Big parties', 'Intimate dinners', 'soft'),
('love_drunk', 'this_or_that', 'Wearing promise rings or waiting for engagement rings?', 'Promise rings', 'Waiting for engagement', 'soft'),
('love_drunk', 'this_or_that', 'Sunday morning pancakes or Sunday morning lazy cuddles?', 'Pancakes', 'Lazy cuddles', 'soft'),
('love_drunk', 'this_or_that', 'Reading books together or writing notes to each other?', 'Reading books', 'Writing notes', 'soft'),
('love_drunk', 'this_or_that', 'Planting a garden together or decorating a home together?', 'Planting garden', 'Decorating home', 'soft'),
('love_drunk', 'this_or_that', 'Celebrating anniversaries annually or monthly mini anniversaries?', 'Annually', 'Monthly mini', 'soft'),
('love_drunk', 'this_or_that', 'Love language: time spent or thoughtful gestures?', 'Time spent', 'Thoughtful gestures', 'soft'),
('love_drunk', 'this_or_that', 'Building a business together or supporting separate careers?', 'Business together', 'Separate careers', 'standard'),
('love_drunk', 'this_or_that', 'Merging friend groups or maintaining separate friend groups?', 'Merging', 'Maintaining separate', 'soft'),
('love_drunk', 'this_or_that', 'Setting couple goals or living spontaneously?', 'Setting goals', 'Living spontaneously', 'soft'),
('love_drunk', 'this_or_that', 'Complimenting each other''s looks or complimenting each other''s hearts?', 'Looks', 'Hearts', 'soft'),
('love_drunk', 'this_or_that', 'Couple therapy proactively or only when necessary?', 'Proactively', 'Only when necessary', 'standard'),
('love_drunk', 'this_or_that', 'Romantic road trip or romantic cruise?', 'Road trip', 'Cruise', 'soft'),
('love_drunk', 'this_or_that', 'Giving each other space or being attached at the hip?', 'Giving space', 'Attached at hip', 'soft'),
('love_drunk', 'this_or_that', 'Wearing matching Halloween costumes or matching ugly sweaters at Christmas?', 'Halloween costumes', 'Ugly sweaters', 'soft'),
('love_drunk', 'this_or_that', 'Cooking a fancy meal at home or going to a Michelin-star restaurant?', 'Fancy meal at home', 'Michelin-star', 'soft'),
('love_drunk', 'this_or_that', 'Spontaneous love notes or pre-planned love letters?', 'Spontaneous', 'Pre-planned', 'soft'),
('love_drunk', 'this_or_that', 'Couples game night or couples workout?', 'Game night', 'Workout', 'soft'),
('love_drunk', 'this_or_that', 'Joint social media posts or private relationship?', 'Joint posts', 'Private relationship', 'soft'),
('love_drunk', 'this_or_that', 'Love at first sight or love that grows?', 'First sight', 'Love that grows', 'standard'),
('love_drunk', 'this_or_that', 'Future planning: kids early or travel first?', 'Kids early', 'Travel first', 'standard'),
('love_drunk', 'this_or_that', 'Unconditional love or passionate love?', 'Unconditional', 'Passionate', 'standard');

-- Insert Love Drunk Deck - Open Ended (75 cards) - Part 1
INSERT INTO public.cards (deck_id, subtype, text, spice) VALUES
('love_drunk', 'open_ended', 'When did you first realize you loved me?', 'soft'),
('love_drunk', 'open_ended', 'What''s your favorite non-sexual way to be intimate with me?', 'soft'),
('love_drunk', 'open_ended', 'How do you picture us celebrating our 10th anniversary?', 'soft'),
('love_drunk', 'open_ended', 'What do you think our song should be and why?', 'soft'),
('love_drunk', 'open_ended', 'How do you define romance?', 'soft'),
('love_drunk', 'open_ended', 'What everyday moment makes you feel connected to me?', 'soft'),
('love_drunk', 'open_ended', 'How do you want to be comforted when you''re sad?', 'soft'),
('love_drunk', 'open_ended', 'What is one thing I do that makes you feel cherished?', 'soft'),
('love_drunk', 'open_ended', 'How do you envision our wedding day, if we choose that?', 'standard'),
('love_drunk', 'open_ended', 'What family traditions do you want to create with me?', 'soft'),
('love_drunk', 'open_ended', 'What does emotional commitment look like to you?', 'standard'),
('love_drunk', 'open_ended', 'What small gesture of love do you appreciate most?', 'soft'),
('love_drunk', 'open_ended', 'How do you feel about writing love letters?', 'soft'),
('love_drunk', 'open_ended', 'What is your love language and how can I speak it better?', 'soft'),
('love_drunk', 'open_ended', 'How do you see us growing together over the years?', 'soft'),
('love_drunk', 'open_ended', 'What does "home" mean to you when you think of us?', 'soft'),
('love_drunk', 'open_ended', 'Describe a perfect lazy Sunday with me.', 'soft'),
('love_drunk', 'open_ended', 'What are three things you admire about me?', 'soft'),
('love_drunk', 'open_ended', 'What do you hope our life looks like in five years?', 'soft'),
('love_drunk', 'open_ended', 'How do you want to handle tough times together?', 'standard'),
('love_drunk', 'open_ended', 'How do you feel about renewing vows years down the line?', 'standard'),
('love_drunk', 'open_ended', 'What does loyalty mean in a loving partnership?', 'standard'),
('love_drunk', 'open_ended', 'How do you picture our retirement?', 'soft'),
('love_drunk', 'open_ended', 'What kind of parent do you think I will be, if we choose to have kids?', 'standard'),
('love_drunk', 'open_ended', 'How can I show you more love in small daily ways?', 'soft'),
('love_drunk', 'open_ended', 'What''s one dream trip you want us to take together?', 'soft'),
('love_drunk', 'open_ended', 'What do you think is our strongest shared value?', 'standard'),
('love_drunk', 'open_ended', 'How do you want to be proposed to (or propose)?', 'standard'),
('love_drunk', 'open_ended', 'What does lifelong commitment mean to you?', 'standard'),
('love_drunk', 'open_ended', 'How do you feel when you hear my name?', 'soft'),
('love_drunk', 'open_ended', 'When do you feel most proud of me?', 'soft'),
('love_drunk', 'open_ended', 'What does it mean to you to be my partner?', 'soft'),
('love_drunk', 'open_ended', 'How do you want to celebrate successes together?', 'soft'),
('love_drunk', 'open_ended', 'How do we balance independence and togetherness?', 'standard'),
('love_drunk', 'open_ended', 'What is your favorite memory with me so far?', 'soft'),
('love_drunk', 'open_ended', 'How can I help you feel seen every day?', 'soft'),
('love_drunk', 'open_ended', 'What does a romantic night mean to you?', 'soft'),
('love_drunk', 'open_ended', 'How do you want us to handle disagreements gently?', 'standard'),
('love_drunk', 'open_ended', 'What do you think strengthens our bond most?', 'soft'),
('love_drunk', 'open_ended', 'How do you want to create a sense of adventure in our relationship?', 'soft'),
('love_drunk', 'open_ended', 'What acts of service mean the most to you?', 'soft'),
('love_drunk', 'open_ended', 'How do you feel about pet names?', 'soft'),
('love_drunk', 'open_ended', 'What story do you want our relationship to tell?', 'soft'),
('love_drunk', 'open_ended', 'How do you handle feeling disconnected from me, and what helps you reconnect?', 'standard'),
('love_drunk', 'open_ended', 'What is something small you cherish in our daily life?', 'soft'),
('love_drunk', 'open_ended', 'How do we keep our passion alive through the years?', 'standard'),
('love_drunk', 'open_ended', 'What does partnership look like when times are hard?', 'standard'),
('love_drunk', 'open_ended', 'How do you want me to show up for you when you''re overwhelmed?', 'soft'),
('love_drunk', 'open_ended', 'What''s one thing you want to do with me before we get married (if at all)?', 'standard'),
('love_drunk', 'open_ended', 'What do you see when you imagine us as an old couple?', 'soft'),
('love_drunk', 'open_ended', 'How do we build trust deeper every day?', 'standard'),
('love_drunk', 'open_ended', 'What is a romantic gesture you''d like to receive more?', 'soft'),
('love_drunk', 'open_ended', 'What are your hopes for our family''s future?', 'standard'),
('love_drunk', 'open_ended', 'How should we handle differences in affection needs?', 'standard'),
('love_drunk', 'open_ended', 'What''s your favorite thing about our relationship that others might not see?', 'soft'),
('love_drunk', 'open_ended', 'How do you want me to support your personal growth?', 'soft'),
('love_drunk', 'open_ended', 'What does it mean to you to be my best friend?', 'soft'),
('love_drunk', 'open_ended', 'How do you express love when you''re exhausted or stressed?', 'soft'),
('love_drunk', 'open_ended', 'How would you feel if our roles reversed for a day (responsibilities, etc.)?', 'soft'),
('love_drunk', 'open_ended', 'What conversation do you think every couple should have?', 'standard'),
('love_drunk', 'open_ended', 'How do you show someone you love them without words?', 'soft'),
('love_drunk', 'open_ended', 'What does forgiveness mean in our love story?', 'standard'),
('love_drunk', 'open_ended', 'How do you think love evolves over time?', 'standard'),
('love_drunk', 'open_ended', 'How should we celebrate big moments and milestones?', 'soft'),
('love_drunk', 'open_ended', 'What is your idea of romantic security?', 'standard'),
('love_drunk', 'open_ended', 'What can I do to help you feel more supported?', 'soft'),
('love_drunk', 'open_ended', 'What is one thing about love that you learned from past relationships?', 'standard'),
('love_drunk', 'open_ended', 'How do you handle feeling overlooked?', 'standard'),
('love_drunk', 'open_ended', 'What''s a silly thing we do that you secretly love?', 'soft'),
('love_drunk', 'open_ended', 'How can we make everyday life feel romantic?', 'soft'),
('love_drunk', 'open_ended', 'What worries you about the future and how can I help ease that?', 'standard'),
('love_drunk', 'open_ended', 'How do you want to integrate our families?', 'standard'),
('love_drunk', 'open_ended', 'What''s a romantic ritual you want us to keep or start?', 'soft'),
('love_drunk', 'open_ended', 'How do you define the word "forever" in love?', 'standard'),
('love_drunk', 'open_ended', 'What moment in our relationship made you think this is it?', 'soft');

-- Insert Love Drunk Deck - Say Sip Strip (50 cards)
INSERT INTO public.cards (deck_id, subtype, text, spice) VALUES
('love_drunk', 'say_sip_strip', 'Share the exact moment you knew you were in love. If you can''t, sip or strip.', 'soft'),
('love_drunk', 'say_sip_strip', 'Admit if you ever doubted our relationship at any point. If you refuse, drink.', 'standard'),
('love_drunk', 'say_sip_strip', 'Tell me what you would change about our wedding if we could redo it. Or strip.', 'standard'),
('love_drunk', 'say_sip_strip', 'Describe your fantasy honeymoon with me in detail. Sip if you won''t.', 'soft'),
('love_drunk', 'say_sip_strip', 'Reveal a romantic gesture you secretly didn''t appreciate. Or strip.', 'standard'),
('love_drunk', 'say_sip_strip', 'Tell me something romantic I did that you still think about. If you can''t recall, drink.', 'soft'),
('love_drunk', 'say_sip_strip', 'Admit if you have felt more attracted to someone else since we got serious. Or remove something.', 'standard'),
('love_drunk', 'say_sip_strip', 'Tell me the most meaningful gift I''ve given you. If none come to mind, sip.', 'soft'),
('love_drunk', 'say_sip_strip', 'Reveal if you ever thought of your ex while with me. Or strip.', 'standard'),
('love_drunk', 'say_sip_strip', 'Share one way you feel I could show more love. Or drink.', 'standard'),
('love_drunk', 'say_sip_strip', 'Admit if you have a secret wish for our relationship you think I''ll say no to. Or remove something.', 'standard'),
('love_drunk', 'say_sip_strip', 'Tell me if you ever considered breaking up even while feeling in love. Or sip.', 'standard'),
('love_drunk', 'say_sip_strip', 'Reveal a romantic dream you have that you haven''t told me. Or strip.', 'soft'),
('love_drunk', 'say_sip_strip', 'Describe me in three words and mean it. Or drink.', 'soft'),
('love_drunk', 'say_sip_strip', 'Admit if you ever read my journal or messages out of curiosity. Or remove something.', 'standard'),
('love_drunk', 'say_sip_strip', 'Tell me something romantic you want us to do before we have kids. Or sip.', 'soft'),
('love_drunk', 'say_sip_strip', 'Reveal the moment you first imagined marrying me. Or strip.', 'soft'),
('love_drunk', 'say_sip_strip', 'Tell me a song that makes you think of us every time. Or drink.', 'soft'),
('love_drunk', 'say_sip_strip', 'Admit if you have a secret savings for something romantic. Or remove something.', 'soft'),
('love_drunk', 'say_sip_strip', 'Describe the feeling you get when you imagine life without me. Or sip.', 'standard'),
('love_drunk', 'say_sip_strip', 'Tell me a romantic movie scene you''d like to recreate. Or strip.', 'soft'),
('love_drunk', 'say_sip_strip', 'Reveal one insecurity you have about being loved by me. Or drink.', 'standard'),
('love_drunk', 'say_sip_strip', 'Share a secret note you''ve written about me. Or remove something.', 'soft'),
('love_drunk', 'say_sip_strip', 'Tell me if you ever kept a love letter from an ex. Or sip.', 'standard'),
('love_drunk', 'say_sip_strip', 'Admit if you compare our love story to anyone else''s. Or strip.', 'standard'),
('love_drunk', 'say_sip_strip', 'Describe the perfect date night in one sentence. Or drink.', 'soft'),
('love_drunk', 'say_sip_strip', 'Reveal the most romantic thing someone else has done for you before me. Or remove something.', 'standard'),
('love_drunk', 'say_sip_strip', 'Tell me if you ever thought about proposing sooner than you let on. Or sip.', 'standard'),
('love_drunk', 'say_sip_strip', 'Admit if you have doubts about marriage in general. Or strip.', 'standard'),
('love_drunk', 'say_sip_strip', 'Share a romantic fantasy involving me that you''ve never said. Or drink.', 'standard'),
('love_drunk', 'say_sip_strip', 'Tell me if you ever cried over me. If you won''t share, remove something.', 'soft'),
('love_drunk', 'say_sip_strip', 'Reveal if you ever imagined us having kids and names. Or sip.', 'soft'),
('love_drunk', 'say_sip_strip', 'Share a fear about our future together. Or strip.', 'standard'),
('love_drunk', 'say_sip_strip', 'Tell me if you ever wrote poetry or songs about me. Or drink.', 'soft'),
('love_drunk', 'say_sip_strip', 'Admit if there are parts of me you wish I would change. Or remove something.', 'standard'),
('love_drunk', 'say_sip_strip', 'Reveal a romantic secret no one else knows. Or sip.', 'soft'),
('love_drunk', 'say_sip_strip', 'Describe a moment you felt my love the most. Or strip.', 'soft'),
('love_drunk', 'say_sip_strip', 'Tell me something you love that I do when I''m not aware. Or drink.', 'soft'),
('love_drunk', 'say_sip_strip', 'Admit if you stalked my social media before we got together. Or remove something.', 'soft'),
('love_drunk', 'say_sip_strip', 'Share what you thought of me on our first date. Or sip.', 'soft'),
('love_drunk', 'say_sip_strip', 'Reveal if you ever kept a memento from an ex. Or strip.', 'standard'),
('love_drunk', 'say_sip_strip', 'Tell me a romantic goal you have for us in five years. Or drink.', 'soft'),
('love_drunk', 'say_sip_strip', 'Admit if you ever felt like running when love got hard. Or remove something.', 'standard'),
('love_drunk', 'say_sip_strip', 'Describe your favorite random memory with me. Or sip.', 'soft'),
('love_drunk', 'say_sip_strip', 'Reveal if you ever lied to make me feel better. Or strip.', 'standard'),
('love_drunk', 'say_sip_strip', 'Tell me if there''s a romantic tradition you want us to start. Or drink.', 'soft'),
('love_drunk', 'say_sip_strip', 'Admit if you ever fantasize about a different life. Or remove something.', 'standard'),
('love_drunk', 'say_sip_strip', 'Describe the last time I made you smile unexpectedly. Or sip.', 'soft'),
('love_drunk', 'say_sip_strip', 'Reveal something you would sacrifice for our love. Or strip.', 'standard'),
('love_drunk', 'say_sip_strip', 'Tell me the biggest lesson our love taught you. Or drink.', 'soft');